const us_pres_seed = {
  title: 'U.S. Presidents',
  description: 'How many U.S. Presidents can you name in 60 seconds? Good Luck!',
  instructions: 'All of the answers of the last names of the presidents, presidents that share last names will be answers all at once.',
  input_placeholder: 'Last Name',
  plays: 0,
  total_score: 0,
  username: 'mvcampbell3',
  type: 'history',
  answers: [
    { display_text: 'George Washington', accepted_answers: ['washington'] },
    { display_text: 'John Adams', accepted_answers: ['adams'] },
    { display_text: 'Thomas Jefferson', accepted_answers: ['jefferson'] },
    { display_text: 'James Madison', accepted_answers: ['madison'] },
    { display_text: 'James Monroe', accepted_answers: ['monroe'] },
    { display_text: 'John Quincy Adams', accepted_answers: ['adams'] },
    { display_text: 'Andrew Jackson', accepted_answers: ['jackson'] },
    { display_text: 'Martin Van Buren', accepted_answers: ['vanburen', 'van buren'] },
    { display_text: 'William Henry Harrison', accepted_answers: ['harrison'] },
    { display_text: 'John Tyler', accepted_answers: ['tyler'] },
    { display_text: 'James K. Polk', accepted_answers: ['polk', 'napolean of the south'] },
    { display_text: 'Zachary Taylor', accepted_answers: ['taylor'] },
    { display_text: 'Millard Fillmore', accepted_answers: ['fillmore'] },
    { display_text: 'Franklin Pierce', accepted_answers: ['pierce'] },
    { display_text: 'James Buchanan', accepted_answers: ['buchanan'] },
    { display_text: 'Abraham Lincoln', accepted_answers: ['lincoln'] },
    { display_text: 'Andrew Johnson', accepted_answers: ['johnson'] },
    { display_text: 'Ulysses S. Grant', accepted_answers: ['grant'] },
    { display_text: 'Rutherford B. Hayes', accepted_answers: ['hayes'] },
    { display_text: 'James Garfield', accepted_answers: ['garfield'] },
    { display_text: 'Chester A. Arthur', accepted_answers: ['arthur'] },
    { display_text: 'Grover Cleveland', accepted_answers: ['cleveland'] },
    { display_text: 'Benjamin Harrison', accepted_answers: ['harrison'] },
    { display_text: 'Grover Cleveland', accepted_answers: ['cleveland'] },
    { display_text: 'William Mckinley', accepted_answers: ['mckinley'] },
    { display_text: 'Theodore Roosevelt', accepted_answers: ['roosevelt'] },
    { display_text: 'William H. Taft', accepted_answers: ['taft'] },
    { display_text: 'Woodrow Wilson', accepted_answers: ['wilson'] },
    { display_text: 'Warren G. Harding', accepted_answers: ['harding'] },
    { display_text: 'Calvin Coolidge', accepted_answers: ['coolidge'] },
    { display_text: 'Herbert Hoover', accepted_answers: ['hoover'] },
    { display_text: 'Franklin D. Roosevelt', accepted_answers: ['roosevelt'] },
    { display_text: 'Harry S. Truman', accepted_answers: ['truman'] },
    { display_text: 'Dwight D. Eisenhower', accepted_answers: ['eisenhower'] },
    { display_text: 'John F. Kennedy', accepted_answers: ['kennedy'] },
    { display_text: 'Lyndon B. Johnson', accepted_answers: ['johnson'] },
    { display_text: 'Richard Nixon', accepted_answers: ['nixon'] },
    { display_text: 'Gerald Ford', accepted_answers: ['ford'] },
    { display_text: 'Jimmy Carter', accepted_answers: ['carter'] },
    { display_text: 'Ronald Reagan', accepted_answers: ['reagan'] },
    { display_text: 'George H.W. Bush', accepted_answers: ['bush'] },
    { display_text: 'Bill Clinton', accepted_answers: ['clinton'] },
    { display_text: 'George W. Bush', accepted_answers: ['bush'] },
    { display_text: 'Barack Obama', accepted_answers: ['obama'] },
    { display_text: 'Donald Trump', accepted_answers: ['trump', 'douche'] },
  ]
}

export default us_pres_seed;